# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oppo/R11s/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oppo/R11s

PRODUCT_COPY_FILES += \
    vendor/oppo/R11s/proprietary/vendor/etc/acdbdata/17011/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/17011/Bluetooth_cal.acdb \
    vendor/oppo/R11s/proprietary/vendor/etc/acdbdata/17011/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/17011/General_cal.acdb \
    vendor/oppo/R11s/proprietary/vendor/etc/acdbdata/17011/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/17011/Global_cal.acdb \
    vendor/oppo/R11s/proprietary/vendor/etc/acdbdata/17011/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/17011/Handset_cal.acdb \
    vendor/oppo/R11s/proprietary/vendor/etc/acdbdata/17011/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/17011/Hdmi_cal.acdb \
    vendor/oppo/R11s/proprietary/vendor/etc/acdbdata/17011/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/17011/Headset_cal.acdb \
    vendor/oppo/R11s/proprietary/vendor/etc/acdbdata/17011/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/17011/Speaker_cal.acdb \
    vendor/oppo/R11s/proprietary/vendor/etc/acdbdata/17021/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/17021/Bluetooth_cal.acdb \
    vendor/oppo/R11s/proprietary/vendor/etc/acdbdata/17021/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/17021/General_cal.acdb \
    vendor/oppo/R11s/proprietary/vendor/etc/acdbdata/17021/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/17021/Global_cal.acdb \
    vendor/oppo/R11s/proprietary/vendor/etc/acdbdata/17021/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/17021/Handset_cal.acdb \
    vendor/oppo/R11s/proprietary/vendor/etc/acdbdata/17021/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/17021/Hdmi_cal.acdb \
    vendor/oppo/R11s/proprietary/vendor/etc/acdbdata/17021/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/17021/Headset_cal.acdb \
    vendor/oppo/R11s/proprietary/vendor/etc/acdbdata/17021/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/17021/Speaker_cal.acdb \
    vendor/oppo/R11s/proprietary/vendor/etc/qdcm_calib_data_oppo17011samsung_sofeg01_s_1080p_cmd_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_oppo17011samsung_sofeg01_s_1080p_cmd_mode_dsi_panel.xml \
    vendor/oppo/R11s/proprietary/vendor/etc/qdcm_calib_data_oppo17021samsung_sofeg01_s_1080p_cmd_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_oppo17021samsung_sofeg01_s_1080p_cmd_mode_dsi_panel.xml \
    vendor/oppo/R11s/proprietary/vendor/firmware/tp/17011/17011_FW_S3508_SYNAPTICS.img:$(TARGET_COPY_OUT_VENDOR)/firmware/tp/17011/17011_FW_S3508_SYNAPTICS.img \
    vendor/oppo/R11s/proprietary/vendor/firmware/tp/17011/17011_Limit_data.img:$(TARGET_COPY_OUT_VENDOR)/firmware/tp/17011/17011_Limit_data.img \
    vendor/oppo/R11s/proprietary/vendor/firmware/tp/17021/17021_FW_S3508_SYNAPTICS.img:$(TARGET_COPY_OUT_VENDOR)/firmware/tp/17021/17021_FW_S3508_SYNAPTICS.img \
    vendor/oppo/R11s/proprietary/vendor/firmware/tp/17021/17021_Limit_data.img:$(TARGET_COPY_OUT_VENDOR)/firmware/tp/17021/17021_Limit_data.img \
    vendor/oppo/R11s/proprietary/vendor/lib/hw/gatekeeper.sdm660.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gatekeeper.sdm660.so \
    vendor/oppo/R11s/proprietary/vendor/lib/hw/keystore.sdm660.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/keystore.sdm660.so \
    vendor/oppo/R11s/proprietary/vendor/lib64/hw/gatekeeper.sdm660.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gatekeeper.sdm660.so \
    vendor/oppo/R11s/proprietary/vendor/lib64/hw/keystore.sdm660.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/keystore.sdm660.so
